// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArs6-2DXAyI604Jc2IYk0Kflr7fcYqzRI',
    appId: '1:1037094854313:web:3510ffe8bdd83a177953b8',
    messagingSenderId: '1037094854313',
    projectId: 'playlist-ae81d',
    authDomain: 'playlist-ae81d.firebaseapp.com',
    storageBucket: 'playlist-ae81d.appspot.com',
    measurementId: 'G-G93PET2W6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpKSz9G_ZK0DupDS-KCxrNXs6hBuZ7udU',
    appId: '1:1037094854313:android:2723a52dde29951a7953b8',
    messagingSenderId: '1037094854313',
    projectId: 'playlist-ae81d',
    storageBucket: 'playlist-ae81d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl4TYzSr4Ruanro2CUbaR8r5UBYqLoQ2Y',
    appId: '1:1037094854313:ios:bb60f3dfed80c2787953b8',
    messagingSenderId: '1037094854313',
    projectId: 'playlist-ae81d',
    storageBucket: 'playlist-ae81d.appspot.com',
    iosClientId:
        '1037094854313-v3es9bcr723dfcpe58uaesh384omnv33.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl4TYzSr4Ruanro2CUbaR8r5UBYqLoQ2Y',
    appId: '1:1037094854313:ios:bb60f3dfed80c2787953b8',
    messagingSenderId: '1037094854313',
    projectId: 'playlist-ae81d',
    storageBucket: 'playlist-ae81d.appspot.com',
    iosClientId:
        '1037094854313-v3es9bcr723dfcpe58uaesh384omnv33.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
